// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhqGfEXcjtF4L8seYxAhuuSFVr0D9yddc',
    appId: '1:148127360294:web:2fc592d2b477c83fa70de7',
    messagingSenderId: '148127360294',
    projectId: 'employee-db-96a28',
    authDomain: 'employee-db-96a28.firebaseapp.com',
    databaseURL: 'https://employee-db-96a28-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-96a28.firebasestorage.app',
    measurementId: 'G-R1Q8P0JXXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCcxmB5-uN7CoI3R53CHlHbg6BP_Ucew',
    appId: '1:148127360294:android:bb91584dedee18f4a70de7',
    messagingSenderId: '148127360294',
    projectId: 'employee-db-96a28',
    databaseURL: 'https://employee-db-96a28-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-96a28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1aKRNA1lJWtYsw5aZdvP_912j-S-xB18',
    appId: '1:148127360294:ios:ae38f3e4732e0d23a70de7',
    messagingSenderId: '148127360294',
    projectId: 'employee-db-96a28',
    databaseURL: 'https://employee-db-96a28-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-96a28.firebasestorage.app',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1aKRNA1lJWtYsw5aZdvP_912j-S-xB18',
    appId: '1:148127360294:ios:ae38f3e4732e0d23a70de7',
    messagingSenderId: '148127360294',
    projectId: 'employee-db-96a28',
    databaseURL: 'https://employee-db-96a28-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-96a28.firebasestorage.app',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhqGfEXcjtF4L8seYxAhuuSFVr0D9yddc',
    appId: '1:148127360294:web:961b07592fb73885a70de7',
    messagingSenderId: '148127360294',
    projectId: 'employee-db-96a28',
    authDomain: 'employee-db-96a28.firebaseapp.com',
    databaseURL: 'https://employee-db-96a28-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-96a28.firebasestorage.app',
    measurementId: 'G-45JG9WZL67',
  );
}
